CREATE TABLE "smartorder_backroom_snapshot" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location" varchar(256) NOT NULL,
	"imageUrl" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "smartorder_catalog_item" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(256) NOT NULL,
	"vendor" varchar(256),
	"category" varchar(128),
	"packSize" varchar(64),
	"unitType" varchar(32) DEFAULT 'case' NOT NULL,
	"barcode" varchar(64),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "smartorder_list_item" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listId" uuid NOT NULL,
	"catalogItemId" uuid NOT NULL,
	"targetCases" integer DEFAULT 0 NOT NULL,
	"targetUnits" integer DEFAULT 0 NOT NULL,
	"scannedCases" integer DEFAULT 0 NOT NULL,
	"scannedUnits" integer DEFAULT 0 NOT NULL,
	"sortOrder" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "smartorder_list" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(256) NOT NULL,
	"status" varchar(16) DEFAULT 'draft' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "smartorder_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "smartorder_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "smartorder_list_item" ADD CONSTRAINT "smartorder_list_item_listId_smartorder_list_id_fk" FOREIGN KEY ("listId") REFERENCES "public"."smartorder_list"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "smartorder_list_item" ADD CONSTRAINT "smartorder_list_item_catalogItemId_smartorder_catalog_item_id_fk" FOREIGN KEY ("catalogItemId") REFERENCES "public"."smartorder_catalog_item"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "backroom_snapshot_created_at_idx" ON "smartorder_backroom_snapshot" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "catalog_item_name_idx" ON "smartorder_catalog_item" USING btree ("name");--> statement-breakpoint
CREATE INDEX "catalog_item_vendor_idx" ON "smartorder_catalog_item" USING btree ("vendor");--> statement-breakpoint
CREATE INDEX "list_item_list_idx" ON "smartorder_list_item" USING btree ("listId");--> statement-breakpoint
CREATE INDEX "list_item_catalog_idx" ON "smartorder_list_item" USING btree ("catalogItemId");--> statement-breakpoint
CREATE INDEX "list_updated_at_idx" ON "smartorder_list" USING btree ("updatedAt");--> statement-breakpoint
CREATE INDEX "name_idx" ON "smartorder_post" USING btree ("name");